version: '3'

services:
  webserver:
    build: ./webserver
    ports:
      - "8443:8443"
    networks:
      - ctfnet

  # challenger:
  #   build: ./challenger
  #   networks:
  #     - ctfnet
  #   depends_on:
  #     - webserver

networks:
  ctfnet:
    driver: bridge
